version: 1
listener:
  address: tcp://0.0.0.0:9211
  access_log_path: /dev/stdout
admin:
  address: tcp://0.0.0.0:9901
  access_log_path: /dev/stdout
discovery_service:
  lb: nginx:80
  tls: false
  refresh_delay_ms: 10000
  connect_timeout_ms: 100
sds:
  lb: sds:8080
  tls: false
  refresh_delay_ms: 1000
  connect_timeout_ms: 1500
statsd:
  address: statsd-exporter:9125
