AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true

Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
