AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'test/grpc/lib/health_pb.rb'
    - 'test/grpc/lib/health_services_pb.rb'

Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Naming/UncommunicativeMethodParamName:
  Enabled: false
